.\"
.\" Copyright 1998 by the Massachusetts Institute of Technology.
.\"
.\" Permission to use, copy, modify, and distribute this
.\" software and its documentation for any purpose and without
.\" fee is hereby granted, provided that the above copyright
.\" notice appear in all copies and that both that copyright
.\" notice and this permission notice appear in supporting
.\" documentation, and that the name of M.I.T. not be used in
.\" advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.
.\" M.I.T. makes no representations about the suitability of
.\" this software for any purpose.  It is provided "as is"
.\" without express or implied warranty.
.\"
.TH ARES_GETADDRINFO 3 "6 November 2018"
.SH NAME
ares_getaddrinfo \- Initiate a host query by name and service
.SH SYNOPSIS
.nf
.B #include <ares.h>
.PP
.B typedef void (*ares_addrinfo_callback)(void *\fIarg\fP, int \fIstatus\fP,
.B 	int \fItimeouts\fP, struct ares_addrinfo *\fIres\fP)
.PP
.B void ares_getaddrinfo(ares_channel \fIchannel\fP,
.B 	const char *\fIname\fP, const char *\fIservice\fP,
.B 	const struct ares_addrinfo *\fIhints\fP,
.B 	ares_addrinfo_callback \fIcallback\fP, void *\fIarg\fP)
.fi
.SH DESCRIPTION
The
.B ares_getaddrinfo
function initiates a host query by name on the name service channel
identified by
.IR channel .
The
.I name
and
.I service
parameters give the hostname and service as NULL-terminated C strings.
The
.I hints
parameter is an
.BR "ares_addrinfo"
structure. Every field except
.I ai_family,
.I ai_socktype,
.I ai_protocol,
and
.I ai_flags
must be set to zero.
.TP
.I ai_family
Specifies desired address family. AF_UNSPEC means
return both AF_INET and AF_INET6.
.TP
.I ai_socktype
Specifies desired socket type, for example SOCK_STREAM or SOCK_DGRAM.
Setting this to 0 means any type.
.TP
.I ai_protocol
Setting this to 0 means any protocol.
.TP
.I ai_flags
Specifies additional options, see below.
.PP
If ARES_AI_NUMERICSERV option is set
.I service
field will be treated as a numeric value.
If ARES_AI_CANONNAME is set the first ares_addrinfo structure
will contain a canonical name of the host in ai_canonname field.
.PP
When the query is complete or has failed, the ares
library will invoke \fIcallback\fP.  Completion or failure of the query may
happen immediately, or may happen during a later call to
\fIares_process(3)\fP, \fIares_destroy(3)\fP or \fIares_cancel(3)\fP.
.PP
The callback argument
.I arg
is copied from the
.B ares_getaddrinfo
argument
.IR arg .
The callback argument
.I status
indicates whether the query succeeded and, if not, how it failed.  It
may have any of the following values:
.TP
.B ARES_SUCCESS
The host lookup completed successfully.
.TP
.B ARES_ENOTIMP
The ares library does not know how to look up addresses of type
.IR family .
.TP
.B ARES_ENOTFOUND
The requested host
.I name
is not found.
.TP
.B ARES_ESERVICE
The requested
.I service
is not found.
.TP
.B ARES_ENOMEM
Memory was exhausted.
.TP
.B ARES_ECANCELLED
The query was cancelled.
.TP
.B ARES_EDESTRUCTION
The name service channel
.I channel
is being destroyed; the query will not be completed.
.PP
The callback argument
.I timeouts
reports how many times a query timed out during the execution of the
given request.
.PP
On successful completion of the query, the callback argument
.I res
points to a
.B struct ares_addrinfo
containing the addresses of the host returned by the query.
The result is not sorted in any way and ignores sortlist.
The ares will not attempt to free the memory pointed to by
.IR res
it is the caller's responsibility to free the resulting ares_addrinfo
structure using
.BR ares_freeaddrinfo (3)
when it is no longer needed.  If the query did not complete successfully,
.I res
will be
.BR NULL .
.SH SEE ALSO
.BR ares_freeaddrinfo (3),
.BR ares_gethostbyname (3)
.BR ares_process (3),
.SH CAVEATS
This function is under development. It only supports a minimum feature set
of the function
.B getaddrinfo
defined in RFC-3493. It also does not support the destination address selection
algorithm defined in RFC-6724.
.SH AUTHOR
Andrew Selivanov <andrew.selivanov@gmail.com>, on behalf of Crazy Panda http://www.crazypandagames.com
.PP
Christian Ammer
