# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: OpenWatcom
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-openwatcom
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    name: OpenWatcom
    steps:
      - uses: open-watcom/setup-watcom@7ef247f4cdd25d29b7757ae9908655d253d3e13c # v0
      - name: Checkout Source
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: configure
        run: buildconf.bat
        shell: cmd
      - name: Build c-ares
        run: |
          wmake -u -f Makefile.Watcom
      - name: distclean
        run: |
          wmake -u -f Makefile.Watcom clean

