# Copyright (C) The c-ares project and its contributors
# SPDX-License-Identifier: MIT
name: OpenWatcom
on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.ref }}-openwatcom
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    name: OpenWatcom
    steps:
      - uses: open-watcom/setup-watcom@f0c24a936512429598af01e37fb4a96e8faece74 # v1
      - name: Checkout Source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: configure
        run: buildconf.bat
        shell: cmd
      - name: Build c-ares
        run: |
          wmake -u -f Makefile.Watcom
      - name: distclean
        run: |
          wmake -u -f Makefile.Watcom clean

